CREATE SCHEMA RentCar;
GO
CREATE TABLE RentCar.CLIENTE (
   NIF INT PRIMARY KEY,
   Nome VARCHAR(50) NOT NULL,
   Endereco VARCHAR(150) NOT NULL,
   NCarta INT UNIQUE NOT NULL
);
CREATE TABLE RentCar.BALCAO (
   Numero INT PRIMARY KEY,
   Nome VARCHAR(50) NOT NULL,
   Endereco VARCHAR(150) NOT NULL
);
CREATE TABLE RentCar.TIPO_VEICULO (
   Codigo INT PRIMARY KEY,
   Designacao VARCHAR(200) NOT NULL,
   ArCondicionado BIT NOT NULL
);
CREATE TABLE RentCar.VEICULO (
   Matricula CHAR(8) PRIMARY KEY,
   Marca VARCHAR(20) NOT NULL,
   Ano INT NOT NULL,
   Tipo INT NOT NULL REFERENCES RentCar.TIPO_VEICULO(Codigo)
);
CREATE TABLE RentCar.ALUGUER (
   Numero INT PRIMARY KEY IDENTITY(1,1),
   Data DATE NOT NULL,
   Duracao INT NOT NULL,
   Titular INT NOT NULL REFERENCES RentCar.CLIENTE(NIF),
   [Local] INT NOT NULL REFERENCES RentCar.BALCAO(Numero),
   Objeto CHAR(8) NOT NULL REFERENCES RentCar.VEICULO(Matricula)
);
CREATE TABLE RentCar.VEICULO_LIGEIRO (
   VeiculoBase CHAR(8) PRIMARY KEY REFERENCES RentCar.VEICULO(Matricula),
   NLugares TINYINT NOT NULL CHECK(NLugares < 10),
   NPortas TINYINT NOT NULL,
   Combustivel VARCHAR(20) NOT NULL
);
CREATE TABLE RentCar.VEICULO_PESADO (
   VeiculoBase CHAR(8) PRIMARY KEY REFERENCES RentCar.VEICULO(Matricula),
   Peso INT NOT NULL,
   Passageiros INT NOT NULL,
);
CREATE TABLE RentCar.SIMILARIDADE (
   Veiculo1 CHAR(8) REFERENCES RentCar.VEICULO(Matricula),
   Veiculo2 CHAR(8) REFERENCES RentCar.VEICULO(Matricula),
   PRIMARY KEY(Veiculo1, Veiculo2)
);